### ISSUE TITLE
Error: No Java11 or Java17 found

### ISSUE THREAD

**Issue by fangrh** [zao111222333/spinalhdl-online#4]
Produce steps
1. Create container
2. Enter container in browser (ex. localhost:8848)
3. cd SpinalTemplateSbt

Scala(Metals) error occur: Unable to find a Java 11 or Java 17 installation on this computer. To fix this problem, update the "metals.javaHome" setting to point to a Java 11 or Java 17 home directory or select a version to install automatically

**Comment by zao111222333** [comment]
Thank you for reminding me that this repository should be maintained!

SpinalHDL require Java8 so there is only JDK8 within our docker image, and I find that Java8 is supported by `Metals` still for the latest version. So I have no idea about the error you meet, but **I will recreate this image with all latest packages in this week**.

I have fellow the [`README`](https://github.com/zao111222333/spinalhdl-online#usage) in a new server, and here is the demo I get (the URL is expected to be valid for at least six months): 
http://175.178.13.102:8848/?folder=/SpinalHDL/DIR/SpinalTemplate

My command for the demo:
```
docker run -itd \
  --restart=always \
  -p 8848:8080 \
  -p 2222:22 \
  -e USER=username \
  -e PASSWORD=123456 \
  -e WORKDIR=/SpinalHDL/ \
  -e GDK_MAX_PORT=2 \
  -v ~/SpinalHDL-Share:/SpinalHDL/ \
  -v ~/KEY:/KEY \
  zao111222333/spinalhdl-online
```

Here are some suggestions that may help:
+ At first time you open one sbt project, when there are message appear at right bottom corner, please click `import build`.
+ Your dir should at the root of sbt project, e.g. `http://xxxx/?folder=/SpinalHDL/DIR/SpinalTemplate`.
+ Since it it a long term since last update, please try not to update any packages.

**Comment by zao111222333** [comment]
> Thanks for your reply. A remarkable project! And indeed I have got it work in my own server and this project is just what I am looking for, especially, the gtkwave-online module. I have opend the URL you provided, and still show this error. I take a snape shoot and upload in the workspace in http://175.178.13.102:8848/?folder=/SpinalHDL/DIR/SpinalTemplate.

Hi, I am happy to inform you that this issue was fixed and `SpinalHDL-Online` have make all packages up-to-date ... after struggle with some dependencies conflicts. And the latest image already have been upload to Dockerhub.

And please notice that only `Mill` approaching is ready in that image form now, which seems work better for me. But you can also install sbt tool-chain by the help of `Metals`!

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/57790433/236583560-fc57a108-5b4b-41e2-8f5c-7536c821a826.png">
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/57790433/236583215-cd9d47a6-6e87-47a8-b8bf-13b73f245a69.png">
